projects:
  profile:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        graphQLApiId: vjc4fpbmirfj7fnnyh43tcbjyi
      endpoints:
        prod: >-
          https://3df2slfjlraaldvnpgwl2isp6i.appsync-api.us-east-1.amazonaws.com/graphql
